---
# handlers file for pg_database
- name: restart postgresql
  systemd:
    name: postgresql-11
    state: restarted

- name: reload postgresql
  systemd:
    name: postgresql-11
    state: reloaded
