- name: Install TimescaleDB repo
  yum_repository:
    name: timescale_timescaledb
    description: Timescale Repo
    baseurl: https://packagecloud.io/timescale/timescaledb/el/7/\$basearch
    file: external_repos
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/timescale/timescaledb/gpgkey
    gpgcheck: no
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
   
- name: Install TimescaleDB-11
  yum:
    name: timescaledb-postgresql-11
    state: present

- name: Check if timescaledb tune has been run
  find:
    path: '/tmp/'
    pattern: 'timescaledb\_tune\.backup'
    use_regex: yes
  register: found_files

- name: Configure postgres for timescaledb
  command: "timescaledb-tune -yes"
  when:  found_files.matched == 0
  notify: restart postgres
