---
# tasks file for ts_database

#TODO:  Determine if the Timescaledb-postgresql-11 package is/should be signed. Appears not to be. 



- name: Install PostgreSQL
  # TODO: currently only for CentOS. Expand to other distributions, provide error/error handling.
  block: 

    - name: install EPEL (pre-requiste)
      package:
          name: 
            - epel-release
          state: present
      when: ansible_os_family == 'RedHat'

    - name: Install PostgreSQL repo
      yum_repository:
        name: pgpd
        description: PostgreSQL repo
        baseurl: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/   
        file: external_repos
        gpgcheck: yes
        gpgkey: https://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
         
      when: ansible_os_family == 'RedHat'
     
    - name: Prevent dependencies being resolved by base repo (CentOS)
      block:
        - name: Exclude postgres* in base
          ini_file:
            path: /etc/yum.repos.d/CentOS-Base.repo
            section: base
            option: exclude
            value: 'postgres*'

        - name: Exclude postgres* in updates
          ini_file:
            path: /etc/yum.repos.d/CentOS-Base.repo
            section: updates
            option: exclude
            value: 'postgres*' 
  
    - name: Install PostgreSQL 11 Server
      yum:
        name: postgresql11-server
        state: present
  become: yes

- name: Configure Postgres
  block:
    - name: Determine if db is already initialized
      find:
        path: '/var/lib/pgsql/11/data'
      register: found_files      

    - name: Initialize postgres database 
      command: '/usr/pgsql-11/bin/postgresql-11-setup initdb'
      when: found_files.msg == ""  and found_files.matched == 0
      notify: restart postgres
  
    - name: Autostart postgres on boot
      systemd: 
        name: postgresql-11
        enabled: yes

- name: Install TimescaleDB
  block:

    - name: Install TimescaleDB repo
      yum_repository:
        name: timescale_timescaledb
        description: Timescale Repo
        baseurl: https://packagecloud.io/timescale/timescaledb/el/7/\$basearch
        file: external_repos
        repo_gpgcheck: yes
        gpgkey: https://packagecloud.io/timescale/timescaledb/gpgkey
        gpgcheck: no
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
        metadata_expire: 300
        
       
    - name: Install TimescaleDB-11
      yum:
        name: timescaledb-postgresql-11
        state: present

  when: ansible_os_family == 'RedHat'
  become: yes
         
