- name: Deploy the `common` role
  import_playbook: deploy_common.yml
  tags: common

- name: Install and configure postgresql
  import_playbook: deploy_postgres.yml
  tags: postgresql

- name: Copy certificates for nginx TLS
  import_playbook: copy_certificates.yml
  tags: certs

- name: Install and configure nginx 
  import_playbook: deploy_nginx.yml
  tags: nginx

- hosts: apolloweb, apollosql
  tasks:
    - name: open port 80
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: open port 443
      firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes
  tags: firewall
  become: yes

- name: Apply apollo_api role
  hosts: apolloweb
  tags: 'apollo_api'
  roles: 
    - 'apollo_api'
  vars:
    apollo_flask_log_directory: '/var/log/apollo_flask'
  become: yes

- name: Apply apollo_monitor role
  hosts: apollosql
  tags: apollo_monitor
  roles:  
    - apollo_monitor
  become: yes 
  
- name: Apply apollo_docs role
  tags: apollo_docs
  hosts: apollosql
  roles:
    - apollo_docs
  become: yes
 
