
- name: Install pdpg repo and set installation facts
  hosts:
    - apollosql
  tasks:
    - yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
    - set_fact:  
        postgresql_version: "12"
        postgresql_data_dir: "/var/lib/pgsql/12/data"
        postgresql_bin_path: "/usr/pgsql-12/bin"
        postgresql_config_path: "/var/lib/pgsql/12/data"
        postgresql_daemon: postgresql-12
        postgresql_packages:
            - postgresql12
            - postgresql12-server
            - postgresql12-contrib
            - postgresql12-libs
  become: yes

- name: Setup apollosql with `geerlingguy.postgresql` role
  hosts:
    - apollosql
  roles:
    - 'geerlingguy.postgresql'
  become: yes
  vars:
    postgresql_databases:
        - name: '{{ apollo_site_database_name }}'
          owner: '{{ apollo_site_database_user }}'
        - name: '{{ apollo_monitor_postgresql_backend_database_name }}'
    postgresql_users:
        - name: '{{ apollo_site_database_user }}'
          password: '{{ apollo_site_database_password }}'
        - name: '{{ apollo_monitor_postgresql_backend_database_user }}'
          password: '{{ apollo_monitor_postgresql_backend_database_password }}'
    postgresql_global_config_options:
        - option: listen_addresses
          value: '*'
    postgresql_hba_entries:
        - type: local
          database: all
          user: postgres
          auth_method: peer
        - type: local
          database: '{{ apollo_site_database_name }}'
          user: '{{ apollo_monitor_postgresql_backend_database_user }}'
          auth_method: peer
        - type: local
          database: '{{ apollo_monitor_postgresql_backend_database_name }}'
          user: '{{ apollo_monitor_postgresql_backend_database_user }}'
          auth_method: peer

- name: Finish configuration of postgres
  hosts: apollosql
  roles:
    - apollo_pg
  become: yes
