

- hosts: databases
  vars:
    login_host: apollotestdb.cya9db53pp70.us-east-1.rds.amazonaws.com
    login_user: apollodevdb
    login_password: "{{ lookup('file', 'secrets/rds_password.txt') }}"
    ssl_mode: require  # or verify-ca / verify-full
  tasks:
  - import_tasks: db.yaml
# TODO: pg_dump "APOLLO_DB_NAME_HERE" > /some/backup/location/APOLLO_DB_NAME_HERE.dump

# TODO: latest version of stuff for test, pinned to some "latest working" for prod
