---
# handlers file for apollo_pg
- name: restart postgresql
  systemd:
    name: '{{ postgresql_daemon }}'
    state: restarted

- name: reload postgresql
  systemd:
    name: '{{ postgresql_daemon }}'
    state: reloaded
