---
# tasks file for apollo_monitor

- name: Setup dev environmnet
  include_tasks: dev_setup.yml
  when: lifecycle_state == 'dev'

- name: Install grafana
  include_tasks: install_grafana.yml

- name: Configure grafana
  include_tasks: configure_grafana.yml

- name: Set up user accounts
  include_tasks: user_accounts.yml
    
- name: Provision dashboards
  include_tasks: provision_dashboards.yml

- name: Provision datasources
  include_tasks: provision_datasources.yml
   
   
   
   
   
   
   
   
