---
# tasks file for apollo_monitor

- name: Install grafana
  include_tasks: install_grafana.yml

- name: Configure grafana
  include_tasks: configure_grafana.yml

- name: Set up user accounts
  include_tasks: user_accounts.yml
  
