
- name: create a group for Peter
  group:
    name: peter
    state: present
  become: yes

- name: create an account for Peter
  user:
    name: peter
    shell: /bin/bash
    password: $6$JnCoZLYa$V8TwB3aKl/vTpo/lQA4klAhtZd6e3lM65D32SIn6pYh8UKaoiclxcTRNrD9wEIVM8XL9OSOaNN864.oNObKTg0



    # (use `mkpasswd --method=sha-512` to create password)
    groups: "peter,{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
    # TODO?: primary group = peter
    append: yes
    create_home: yes
  become: yes

- name: authorize ssh key for Peter
  authorized_key:
    user: peter
    state: present
    key: "{{ lookup('file', 'roles/common/files/accounts/keys/id_rsa_peter.pub') }}"
  become: yes

- name: set up git config for Peter
  block:
    - git_config:
        name: core.editor
        value: vi
        scope: global
    - git_config:
        name: user.email
        value: pdragos@u.rochester.edu
        scope: global
    - git_config:
        name: user.name
        value: Peter Dragos
        scope: global
  become: yes
  become_user: peter

- name: fix ll alias
  lineinfile:
    path: /home/peter/.bashrc
    line: "alias ll='ls -lah --color=auto'"
    insertafter: EOF
  become: yes
  become_user: peter
