---
# handlers file for monitoring
- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: update trust anchors
  command: /bin/update-ca-trust
  become: yes
