
#- name: create a group for Peter
#  group:
#    name: pdragos
#    state: present
#  become: yes

#- name: create an account for Peter
#  user:
#    name: pdragos
#    shell: /bin/bash
#    password: $6$JnCoZLYa$V8TwB3aKl/vTpo/lQA4klAhtZd6e3lM65D32SIn6pYh8UKaoiclxcTRNrD9wEIVM8XL9OSOaNN864.oNObKTg0



    # (use `mkpasswd --method=sha-512` to create password)
#    groups: "pdragos,{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
#    # TODO?: primary group = pdragos
#    append: yes
#    create_home: yes
#  become: yes

- name: authorize ssh key for pdragos
  authorized_key:
    user: pdragos
    state: present
    key: "{{ lookup('file', 'keys/id_rsa_peter.pub') }}"
  become: yes

- name: set up git config for pdragos
  block:
    - name: Set git editor
      git_config:
        name: core.editor
        value: vi
        scope: global
    - name: Set git email
      git_config:
        name: user.email
        value: pdragos@u.rochester.edu
        scope: global
    - name: Set git username
      git_config:
        name: user.name
        value: Peter Dragos
        scope: global
  become: yes
  become_user: pdragos

- name: fix ll alias
  lineinfile:
    path: /home/urmc-sh.rochester.edu/pdragos/.bashrc
    line: "alias ll='ls -lah --color=auto'"
    insertafter: EOF
  become: yes
  become_user: pdragos
