- name: install EPEL (pre-requiste)
  package:
      name: 
        - epel-release
      state: present
  when: ansible_os_family == 'RedHat'

- name: Install PostgreSQL repo
  yum_repository:
    name: pgpd
    description: PostgreSQL repo
    baseurl: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/   
    file: external_repos
    gpgcheck: yes
    gpgkey: https://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
     
  when: ansible_os_family == 'RedHat'
 
- name: Prevent dependencies being resolved by base repo (CentOS)
  block:
    - name: Exclude postgres* in base
      ini_file:
        path: /etc/yum.repos.d/CentOS-Base.repo
        section: base
        option: exclude
        value: 'postgres*'

    - name: Exclude postgres* in updates
      ini_file:
        path: /etc/yum.repos.d/CentOS-Base.repo
        section: updates
        option: exclude
        value: 'postgres*' 

- name: Install PostgreSQL 11 Server
  yum:
    name: postgresql11-server
    state: present

- name: Install psycopg2
  yum: 
    name: python2-psycopg2
    state: present
  




