---
# tasks file for pg_database
- name: Set facts
  include_tasks: variables.yml 

- name: Install PostgreSQL
  include_tasks: install.yml
  
- name: Configure PostgreSQL
  include_tasks: configure.yml

- name: Initialize the database
  include_tasks: initialize.yml

