---
# tasks file for apollo_pg
- name: give APOLLO user full access to APOLLO database
  postgresql_privs:
    type: database
    database: "apollo_site"
    privs: ALL
    objs: "apollo_site"
    roles: apollo
    grant_option: no
    state: present
  become_user: postgres

- name: give grafana user read-only access to APOLLO database
  postgresql_privs:
    type: table
    database: "apollo_site"
    privs: SELECT
    objs: ALL_IN_SCHEMA
    roles: grafana
    grant_option: no
    state: present
  become_user: postgres

- name: give grafana user TEMP privs on APOLLO database
  postgresql_privs:
    type: database
    database: "apollo_site"
    privs: TEMP
    objs: "apollo_site"
    roles: grafana
    grant_option: no
    state: present
  become_user: postgres

- name: revoke public privs to APOLLO database
  postgresql_privs:
    type: database
    database: "apollo_site"
    privs: ALL
    objs: "apollo_site"
    role: PUBLIC
    state: absent      
  become_user: postgres

- name: add postgres to the firewall
  firewalld: 
    service: postgresql
    permanent: yes
    immediate: yes
    state: enabled

- name: Copy ssl key
  copy:
    src: server.key
    dest: /var/lib/pgsql/data/server.key
    mode: '0400'
    owner: postgres
    group: postgres
  
- name: Copy root certificate
  copy:
    src: root.crt
    dest: /var/lib/pgsql/data/root.crt
    mode: '0400'
    owner: postgres
    group: postgres

- name: Copy server certificate
  copy: 
    src: server.crt
    dest: /var/lib/pgsql/data/server.crt
    mode: '0400'
    owner: postgres
    group: postgres

- name: Add apollo_site to pg_hba.conf
  postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: hostssl
    users: '{{ apollo_site_database_user }}'
    source: '{{ apollo_site_database_connection_cidr_ip }}'
    method: md5
    databases: '{{ apollo_site_database_name }}'
    owner: postgres
    group: postgres
  notify: reload postgresql

- name: Set postgresql SSL mode to "Require"
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    line: 'ssl = on'
    insertafter: EOF
  notify: restart postgresql

# TODO: revoke apollodevdb privs as well?  or just remove from template0/1 at
# the start?

########################## Last part: set up backups ###########################

# TODO: backups (dumps) down to Z: or something

################################################################################
