
# We install two different utilities that can mount S3 buckets: s3fs and s3ql.
# But in the end we will only use one of them.

##################################### s3fs #####################################

- name: download s3fs
  git:
    repo: https://github.com/s3fs-fuse/s3fs-fuse.git
    dest: /home/apollo/code/s3fs-fuse
  become: yes
  become_user: apollo

- name: install s3fs prereqs (redhat)
  package:
    name:
      - automake
      - fuse
      - fuse-devel
      - gcc-c++
      - git
      - libcurl-devel
      - libxml2-devel
      - make
      - openssl-devel
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install s3fs prereqs (debian)
  package:
    name:
      - automake
      - autotools-dev
      - fuse
      - g++
      - git
      - libcurl4-openssl-dev
      - libfuse-dev
      - libssl-dev
      - libxml2-dev
      - make
      - pkg-config
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: compile s3fs
  command: "{{ item }}"
  with_items:
    - ./autogen.sh
    - ./configure
    - make
  args:
    chdir: /home/apollo/code/s3fs-fuse
    creates: /home/apollo/code/s3fs-fuse/src/s3fs
  become: yes

- name: install s3fs
  command: make install
  args:
    chdir: /home/apollo/code/s3fs-fuse
    creates: /usr/local/bin/s3fs
  become: yes

- name: install S3 credentials
  copy:
    src: passwd-s3fs
    dest: /etc/passwd-s3fs
    owner: root
    group: root
    mode: 0640
  become: yes

##################################### s3ql #####################################

- name: install python developer tools
  package:
    name:
      - "{{ 'python-devel'   if ansible_os_family == 'RedHat' else 'python-dev' }}"
      - "{{ 'python36-devel' if ansible_os_family == 'RedHat' else 'python3-dev' }}"
    state: present
  become: yes

- name: install s3ql prereqs (yum)
  package:
    name:
      - unzip
      - bzip2
      - "{{ 'sqlite-devel' if ansible_os_family == 'RedHat' else 'libsqlite3-dev' }}"
      # TODO?:
      #   systemd-devel
      #   libattr-devel
      #   fuse-devel
      #   psmisc
      #   sqlite
      #   gcc
      #   git
    state: present

- name: install s3ql prereqs (pip)
  pip:
    name: ['apsw', 'pycrypto', 'requests', 'defusedxml', 'llfuse==1.3.5', 'dugong==3.7.3', 'pytest']
    # TODO?:
    # - setuptools, version 1.0 or newer
    # - systemd (optional, for enabling systemd support)
    # - pytest-catchlog
    executable: pip3
    umask: '0022'
  # Those are (mostly) all listed in setup.py, but we seem to need to install
  # them manually.  (see https://github.com/pypa/pip/issues/4780)
  # Note: exact version numbers are used to work aroud
  # https://github.com/ansible/ansible/issues/22399.

- name: extract s3ql source
  unarchive:
    src: s3ql-2.30.tar.bz2
    dest: /home/apollo/code
    creates: /home/apollo/code/s3ql-2.30/setup.py

- name: compile s3ql
  command: 'python3 setup.py build_ext --inplace'
  args:
    chdir: /home/apollo/code/s3ql-2.30
    creates: /home/apollo/code/s3ql-2.30/src/s3ql/deltadump.cpython-34m.so
  become: yes
  # Note: you can test it with `python3 -m pytest tests/`.

- name: install s3ql
  command: python3 setup.py install
  args:
    chdir: /home/apollo/code/s3ql-2.30
    creates: /usr/bin/mount.s3ql
  become: yes

# TODO: creds (http://www.rath.org/s3ql-docs/authinfo.html)

################################### mount it ###################################

- name: create directory to mount s3 bucket
  file:
    path: /mnt/s3
    state: directory
    #mode: 0775  # TODO: I think the file permissions here need to be handled differently. I get an IO error on the second run of this play. See https://serverfault.com/questions/175630/s3fs-input-output-error
  become: yes

- name: mount S3 bucket
  mount:
    path: /mnt/s3
    src: 's3fs#smd-apollo-test'  # TODO: may get renamed
    fstype: fuse
    opts: _netdev,allow_other
    state: mounted
  become: yes

# TODO: create directories (or better, separate buckets to allow simultaneous
# mounting) for test+prod, subdirs for subjects and file types

################################################################################
