---
# tasks file for common
- name: Common software setup
  include_tasks: software_setup.yml

- name: Security stuff
  include_tasks: security_setup.yml

- name: Add/configure user accounts
  include_tasks: user_accounts.yml
  when: lifecycle_state != "prod" #prod uses AD
  

#- name: Install S3 drivers
#  include_tasks: install_s3.yml

# TODO: similar for all hosts, not just remote.  (that config was based on RHEL template, need to compare to Debian.)

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set timezone
  timezone:
    name: America/New_York

  # - name: install ddclient
  #   # TODO: configure+start it
  #   package:
  #     name:
  #       - ddclient
  #     state: present
  #   become: yes
  # TODO: tmux, molly-guard, ...

