- name: Keep postfix stopped
  service:
    name: postfix
    state: stopped
  become: yes

- name: Harden sysctl
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      fs.suid_dumpable = 0
      kernel.core_uses_pid = 1
      kernel.dmesg_restrict = 1
      kernel.kptr_restrict = 2
      kernel.yama.ptrace_scope = 2
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv6.conf.default.accept_redirects = 0

- name: restrict umask
  copy:
    content: "umask 027\n"
    dest: /etc/profile.d/custom_umask.sh
    # TODO: in Ubuntu we should set it in /etc/login.defs
    mode: 0644

### Commented because these aren't in the RHEL repos
#- name: install some security tools
#  package:
#    name:
#      - fail2ban
#      - clamav
#    state: present

#- name: Create fail2ban jail conf file
#  lineinfile:
#    path: /etc/fail2ban/jail.d/from-ansible.conf
#    line: '### Ansible Managed: Manually entered data may be overwritten ###'
#    create: yes

#- name: enable fail2ban ssh jail(s)
#  ini_file:
#    path: /etc/fail2ban/jail.d/from-ansible.conf
#    mode: '644'
#    create: yes
#    section: sshd
#    option: enabled
#    value: 'true'


#- name: enable fail2ban
#  service:
#    name: fail2ban
#    enabled: yes
#    state: started

- name: harden sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0640
    force: yes
    backup: yes
  notify: reload sshd

- name: Increase ssh modulus size
  copy:
    src: moduli.safe
    dest: /etc/ssh/moduli
    force: yes
    backup: yes
    mode: 0640
  notify: reload sshd

- name: add ICMP block 'timestamp-request' to the firewall
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
    icmp_block: timestamp-request

- name: add ICMP block 'timestamp-replay' to the firewall
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
    icmp_block: timestamp-reply
#
# TODO: auto-update clamav data
# TODO: Auter or unattended-upgrade/yum-cron.  careful not to clobber chrome
# or auto-reboot a (local) machine.

