- name: Enable rhel-7-server-optional-rpms
  rhsm_repository:
    name: 'rhel-7-server-optional-rpms'

- name: Enable rhel-7-server-extras-rpms
  rhsm_repository:
    name: 'rhel-7-server-extras-rpms'

- name: install commonly-used software for CentOS/RHEL 7
  package:
    name:
      - git
      - emacs
      - ntp
      - python3-pip 
      - "{{ 'mlocate'      if ansible_os_family == 'RedHat' else 'locate' }}"
      - policycoreutils-python
      - yum-cron
    state: present

- name: Configure yum-cron.conf for security updates
  ini_file:
    path: "{{ item.file }}"
    section: commands
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { file: '/etc/yum/yum-cron.conf', option: 'update_cmd', value: 'security' }
    - { file: '/etc/yum/yum-cron.conf', option: 'download_updates', value: 'yes' }
    - { file: '/etc/yum/yum-cron.conf', option: 'apply_updates', value: 'yes' }
    - { file: '/etc/yum/yum-cron-hourly.conf', option: 'update_cmd', value: 'security' }
    - { file: '/etc/yum/yum-cron-hourly.conf', option: 'download_updates', value: 'yes' }
    - { file: '/etc/yum/yum-cron-hourly.conf', option: 'apply_updates', value: 'yes' }

- name: Start and enable yum-cron
  systemd:
    name: yum-cron
    state: started
    enabled: yes

- name: ensure /usr/local/bin is in PATH (for normal login)
  copy:
    src: custom_path.sh
    dest: /etc/profile.d/custom_path.sh
    mode: 0644

- name: ensure /usr/local/bin is in PATH (for sudo)
  copy:
    content: "Defaults  secure_path=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"\n"
    # If you mess that up, see:
    #   https://askubuntu.com/questions/73864/how-to-modify-an-invalid-etc-sudoers-file
    #   https://askubuntu.com/questions/799669/etc-sudoers-file-corrupted-and-i-cant-run-pkexec-visudo-over-ssh
    dest: /etc/sudoers.d/50-custom-path
    mode: 0440

#    TODO?: may need to reset_connection here.
- name: update pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: enable ntpd
  service:
    name: "{{ 'ntpd'  if ansible_os_family == 'RedHat' else 'ntp' }}"
    enabled: yes
    state: started
