- name: install EPEL (if redhat)
  package:
    name:
      - epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Enable rhel-7-server-optional-rpms
  rhsm_repository:
    name: 'rhel-7-server-optional-rpms'

- name: install commonly-used software
  package:
    name:
      - git
      - emacs
      - ntp
      - "{{ 'python36-pip' if ansible_os_family == 'RedHat' else 'python3-pip' }}"
      - "{{ 'mlocate'      if ansible_os_family == 'RedHat' else 'locate' }}"
      - policycoreutils-python
      - yum-cron
    state: present

- name: ensure /usr/local/bin is in PATH (for normal login)
  copy:
    src: custom_path.sh
    dest: /etc/profile.d/custom_path.sh
    mode: 0644

- name: ensure /usr/local/bin is in PATH (for sudo)
  copy:
    content: "Defaults  secure_path=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"\n"
    # If you mess that up, see:
    #   https://askubuntu.com/questions/73864/how-to-modify-an-invalid-etc-sudoers-file
    #   https://askubuntu.com/questions/799669/etc-sudoers-file-corrupted-and-i-cant-run-pkexec-visudo-over-ssh
    dest: /etc/sudoers.d/50-custom-path
    mode: 0440

#    TODO?: may need to reset_connection here.
- name: update pip
  pip:
    name: pip
    state: latest
    executable: pip

- name: enable ntpd
  service:
    name: "{{ 'ntpd'  if ansible_os_family == 'RedHat' else 'ntp' }}"
    enabled: yes
    state: started
